const mongoose = require("mongoose");

const InvoiceItemSchema = new mongoose.Schema({
  itemId: { type: mongoose.Schema.Types.ObjectId, ref: "Item", required: false },
  name: { type: String, required: true },
  sku: { type: String },
  qty: { type: Number, default: 0 },
  unit: { type: String },
  rate: { type: Number, default: 0 },
  gstRate: { type: Number, default: 0 },
  amount: { type: Number, default: 0 },
  desc: { type: String },
});

const PaymentSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  amount: { type: Number, required: true },
  method: { type: String },
  ref: { type: String },
  note: { type: String },
});

const TotalsSchema = new mongoose.Schema({
  subTotal: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  taxTotal: { type: Number, default: 0 },
  rounding: { type: Number, default: 0 },
  finalTotal: { type: Number, default: 0 },
});

const SalesInvoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: { type: String, required: true, index: true, unique: true },
    invoicePrefix: { type: String, default: "INV" },
    invoiceDate: { type: Date, default: Date.now },
    supplierInvoiceNumber: { type: String },
    supplierDate: { type: Date },

    companyId: { type: mongoose.Schema.Types.ObjectId, ref: "Company", required: true },

    customer: {
      id: { type: mongoose.Schema.Types.ObjectId, ref: "Party" },
      name: { type: String, required: true },
      company: { type: String },
      phone: { type: String },
      email: { type: String },
    },

    items: [InvoiceItemSchema],

    totals: { type: TotalsSchema, default: () => ({}) },

    payments: [PaymentSchema],

    status: { type: String, enum: ["draft", "completed", "cancelled"], default: "draft" },

    meta: {
      createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      notes: { type: String },
      generatedFrom: { type: String }, // e.g. "sales_order", "api"
      isAutoGenerated: { type: Boolean, default: false },
    },
  },
  { timestamps: true }
);

// helper to calculate totals before save if needed
SalesInvoiceSchema.methods.recalculateTotals = function () {
  const subTotal = this.items.reduce((s, it) => s + (Number(it.qty || 0) * Number(it.rate || 0)), 0);
  const taxTotal = this.items.reduce((s, it) => s + (Number(it.qty || 0) * Number(it.rate || 0) * (Number(it.gstRate || 0) / 100)), 0);
  this.totals.subTotal = subTotal;
  this.totals.taxTotal = taxTotal;
  this.totals.finalTotal = Math.round((subTotal + taxTotal - (this.totals.discount || 0) + (this.totals.rounding || 0)) * 100) / 100;
};

module.exports = mongoose.model("SalesInvoice", SalesInvoiceSchema);